SELECT COUNT(ESTATUS) AS CANTIDAD
FROM
(SELECT DISTINCT ROW_NUMBER() OVER (ORDER BY A.TARJETA) AS Nro, 
                ISNULL(A.TARJETA, CONCAT(B.INICIO6_TARJETA,B.FINAL4_TARJETA)) AS TARJETA,
                ISNULL(A.TARJETA6, B.INICIO6_TARJETA) AS INICIO6_TARJETA,
                ISNULL(A.TARJETA4, B.FINAL4_TARJETA) AS FINAL4_TARJETA,
                ISNULL(A.TIPO_TRX, B.TIPO_TRX) AS TIPO_TRX,
                ISNULL(A.TOTAL, B.MONTO) AS MONTO,
                CASE WHEN A.TIPO_TRX IS NULL THEN 'NO CONCILIADO' ELSE 'CONCILIADO' END AS ESTATUS
FROM
(SELECT TARJETA, LEFT(TARJETA, 6) AS TARJETA6, RIGHT(TARJETA,4) AS TARJETA4, TIPO_TRX, TOTAL, FECHA_TRANSACCION, FECHA_RECEPCION, CODIGO_AUTORIZACION
FROM
(SELECT TARJETA, TIPO_TRX, SUM(MONTO) AS TOTAL, FECHA_TRANSACCION, FECHA_RECEPCION, CODIGO_AUTORIZACION
FROM BANSUR
GROUP BY TARJETA, TIPO_TRX, FECHA_TRANSACCION, FECHA_RECEPCION, CODIGO_AUTORIZACION) AS A
WHERE TOTAL <> 0 AND TIPO_TRX = 'PAGO') AS A
FULL JOIN
(SELECT INICIO6_TARJETA, FINAL4_TARJETA, TIPO_TRX, MONTO
FROM
  (SELECT DISTINCT A.INICIO6_TARJETA,
                   A.FINAL4_TARJETA,
                   A.TIPO_TRX,
                   A.MONTO
   FROM
     (SELECT INICIO6_TARJETA,
             FINAL4_TARJETA,
             TIPO_TRX,
             MONTO,
             CODIGO_AUTORIZACION,
             ID_BANCO,
             FECHA_RECEPCION_BANCO
      FROM CLAP) AS A
   LEFT OUTER JOIN
     (SELECT A.INICIO6_TARJETA,
             A.FINAL4_TARJETA,
             A.TIPO_TRX,
             A.MONTO
      FROM
        (SELECT INICIO6_TARJETA,
                FINAL4_TARJETA,
                TIPO_TRX,
                MONTO
         FROM CLAP
         WHERE TIPO_TRX = 'PAGADA') AS A
      INNER JOIN
        (SELECT INICIO6_TARJETA,
                FINAL4_TARJETA,
                TIPO_TRX,
                MONTO
         FROM CLAP
         WHERE TIPO_TRX = 'CANCELADA') AS B ON A.INICIO6_TARJETA = B.INICIO6_TARJETA
      AND A.FINAL4_TARJETA = B.FINAL4_TARJETA
      AND A.MONTO = B.MONTO) AS B ON A.INICIO6_TARJETA = B.INICIO6_TARJETA
   AND A.FINAL4_TARJETA = B.FINAL4_TARJETA
   AND A.MONTO = B.MONTO
   WHERE B.MONTO IS NULL
     AND A.TIPO_TRX = 'PAGADA') AS CONCILIABLE) AS B
     ON A.TARJETA6 = B.INICIO6_TARJETA AND A.TARJETA4 = FINAL4_TARJETA AND A.TOTAL = B.MONTO) AS CONCILIACION