SELECT INICIO6_TARJETA, FINAL4_TARJETA, TIPO_TRX, MONTO
FROM
  (SELECT DISTINCT A.INICIO6_TARJETA,
                   A.FINAL4_TARJETA,
                   A.TIPO_TRX,
                   A.MONTO
   FROM
     (SELECT INICIO6_TARJETA,
             FINAL4_TARJETA,
             TIPO_TRX,
             MONTO,
             CODIGO_AUTORIZACION,
             ID_BANCO,
             FECHA_RECEPCION_BANCO
      FROM CLAP) AS A
   LEFT OUTER JOIN
     (SELECT A.INICIO6_TARJETA,
             A.FINAL4_TARJETA,
             A.TIPO_TRX,
             A.MONTO
      FROM
        (SELECT INICIO6_TARJETA,
                FINAL4_TARJETA,
                TIPO_TRX,
                MONTO
         FROM CLAP
         WHERE TIPO_TRX = 'PAGADA') AS A
      INNER JOIN
        (SELECT INICIO6_TARJETA,
                FINAL4_TARJETA,
                TIPO_TRX,
                MONTO
         FROM CLAP
         WHERE TIPO_TRX = 'CANCELADA') AS B ON A.INICIO6_TARJETA = B.INICIO6_TARJETA
      AND A.FINAL4_TARJETA = B.FINAL4_TARJETA
      AND A.MONTO = B.MONTO) AS B ON A.INICIO6_TARJETA = B.INICIO6_TARJETA
   AND A.FINAL4_TARJETA = B.FINAL4_TARJETA
   AND A.MONTO = B.MONTO
   WHERE B.MONTO IS NULL
     AND A.TIPO_TRX = 'PAGADA') AS CONCILIABLE