SELECT SUM(TOTAL) AS TOTAL_CONCILIABLE, COUNT(TARJETA) AS CONTIDAD_CONCILIABLE
FROM
(SELECT TARJETA, TIPO_TRX, SUM(MONTO) AS TOTAL
FROM BANSUR
GROUP BY TARJETA, TIPO_TRX) AS A
WHERE TOTAL <> 0 AND TIPO_TRX = 'PAGO'


